---
title: "Report"
execute: 
  echo: false      # change to true to show the code
code-fold: false  # change to true to fold the code chunks
---

```{r}
library(tidyverse)
library(ggthemes)

covid <- read_csv("data/clean_covid_formatted.csv")
```

##Viz 1: Scores before Covid by Income Level

```{r}
covid |>
  select(subject, grade,`income_medium`, `income_high`) |>
  pivot_longer(cols = c(-subject, -grade),
               names_to = "income_level",
               values_to = "scores_diff") |>
  mutate(income_level = as.factor(str_to_sentence(str_extract(income_level, "medium|high")))) |>
  mutate(income_level = fct_relevel(income_level, c("Medium", "High")),
         subject = as.factor(subject)) |>
  group_by(income_level, subject) |>
  summarize(mean_scores_diff = mean(scores_diff)) |>
  ggplot(aes(y = mean_scores_diff, x = income_level, fill = income_level)) +
  geom_col() +
  facet_wrap(~subject) +
  labs(x = "Income Level",
       y = "Average Change in Scores from Midterms to Finals",
       title = "Changes in Exam Scores before Covid-19",
       fill = "") +
  theme_solarized() +
  scale_color_solarized() +
  theme(legend.position = "none")
```

## Viz 2: Scores during Covid by Income Level

```{r}
covid |>
  select(subject, grade,`COVID-19 year * Medium income household`, `COVID-19 year * High income household`) |>
  pivot_longer(cols = c(-subject, -grade),
               names_to = "income_level",
               values_to = "scores_diff") |>
  mutate(income_level = as.factor(str_to_sentence(str_extract(income_level, "Medium|High")))) |>
  mutate(income_level = fct_relevel(income_level, c("Medium", "High")),
         subject = as.factor(subject)) |>
  group_by(income_level, subject) |>
  summarize(mean_scores_diff = mean(scores_diff)) |>
  ggplot(aes(y = mean_scores_diff, x = income_level, fill = income_level)) +
  geom_col() +
  facet_wrap(~subject) +
  labs(x = "Income Level",
       y = "Average Change in Scores from Midterms to Finals",
       title = "Changes in Exam Scores during Covid-19",
       fill = "") +
  theme_solarized() +
  theme(legend.position = "none") +
  scale_y_continuous(limits = c(-0.02, 0.07),
                     breaks = seq(0, 0.07, .02))
```

## Observations (Viz 1 & 2)

From our visualizations, we can see that the average difference in final and midterm scores (accounting for income level) 

## Viz 3: Socres Before Covid By Parent Education Level
```{r}
# Viz 3 
covid |>
  select(subject, grade,education_high, education_medium) |>
  pivot_longer(cols = c(-subject, -grade),
               names_to = "education_level",
               values_to = "scores_diff") |>
   mutate(education_level = as.factor(str_to_sentence(str_extract(education_level, "medium|high")))) |>
  mutate(education_level = fct_relevel(education_level, c("Medium", "High")),
         subject = as.factor(subject)) |>
  group_by(education_level, subject) |>
  summarize(mean_scores_diff = mean(scores_diff)) |>
  ggplot(aes(y = mean_scores_diff, x = education_level, fill = education_level)) +
  geom_col() +
  facet_wrap(~subject) +
  labs(x = "Parental Education Level",
       y = "Average Change in Scores Before Covid",
       title = "Changes in Exam Scores before Covid-19",
       fill = "") +
  theme_solarized() +
  theme(legend.position = "none")
```


## Viz 4: Scores During Covid By Parent Education Level

```{r}
# Viz 4: Scores During Covid By Parent Education Level
covid |>
  select(subject, grade,`COVID-19 year * Parental education high`, `COVID-19 year * Parental education medium`) |>
  pivot_longer(cols = c(-subject, -grade),
               names_to = "education_level",
               values_to = "scores_diff") |>
   mutate(education_level = as.factor(str_to_sentence(str_extract(education_level, "medium|high")))) |>
  mutate(education_level = fct_relevel(education_level, c("Medium", "High")),
         subject = as.factor(subject)) |>
  group_by(education_level, subject) |>
  summarize(mean_scores_diff = mean(scores_diff)) |>
  ggplot(aes(y = mean_scores_diff, x = education_level, fill = education_level)) +
  geom_col() +
  facet_wrap(~subject) +
  labs(x = "Parental Education Level",
       y = "Average Change in Scores During Covid",
       title = "Changes in Exam Scores during Covid-19",
       fill = "") +
  theme_solarized()  +
  theme(legend.position = "none")
```
