---
title: "Gabriel DH"
format: html
---

## Key takeaways:

1. Team members should know their responsibilities and the responsibilities of others
2. Team members must make agreements on what needs to be done, and who should do it
3. Team members must be responsible and accountable for completing their own tasks
4. Team members should have specific goals and a timeline for when to complete them
5. Team members should have a sense of trust so that they can speak their minds and set goals as a team

## How to build trust:

- Team members should be able to respect each others' differences and disagree respectfully.
- Team members should focus on harnessing the positive aspects of each member as a unique individual

## Summary:

Effective team work increases efficiency by setting goals that everyone understands, holding members accountable, and understanding how to harness the positive aspects of each member to benefit the project. Trust is necessary for team members to speak freely and share ideas, which supports the project. To build trust, team members must be able to respect each others' differences and respectfully disagree, while also focusing on the positives that each member brings to the team.


**Source:**

<https://www.youtube.com/watch?v=n_UhsBZNADM>
